language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4snapshot'
cache:
    directories:
        - $HOME/.composer/cache/files
script:
    - composer install
    - vendor/bin/phpunit --configuration phpunit.xml.dist --exclude-group=e2e --coverage-clover build/logs/clover.xml
after_script:
    - travis_retry php vendor/bin/php-coveralls -v