language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
directories:
    - $HOME/.composer/cache/files
script:
    - composer install
    - vendor/bin/phpunit --configuration phpunit.xml.dist --group unit-test